In [1]:
import numpy as np
print(np.__version__)

2.0.2


**MEMBUAT ARRAY**

dari list/tuple

In [ ]:
#1D array
arr1 = np.array([1,2,3,4,5])

# 2D array ( matrix)
arr2 = np.array([
    [1,2,3],
    [456]])

#3D array
arr3 = np.array([[[12],
                  [3,4],
                  [5,6]]])

**Array Khusus **

In [8]:
# array nol
zeros = np.zeros((3,4))
print("zeros : ", zeros)
print()

# array 1
ones = np.ones((3,4))
print("ones : ", ones)
print()

# arra7 kosong ( random value )
empty = np.empty((2,2))
print("empty : ", empty)
print()

#array dengan range
range_arr = np.arange(0,10,2)
print("range : ", range_arr)
print()

# array dengan spacing merata
linespace = np.linspace(0,10,5) # 5 nilai dari 0 - 10
print(f"Linspace : ", linespace)
print()

# indetitiy matrix
identity = np.eye(2) # matrix 3 x 3
print("idetntity matrix : ", identity)
print()

# array random
random_Arr = np.random.randn(3,3) #nilai 0-1
print("random array : ",random_Arr)
print()
random_int = np.random.randint(0,10, (3,3))  # integer random
print("randint : ", random_int)



zeros :  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

ones :  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

empty :  [[ 2.5  5. ]
 [ 7.5 10. ]]

range :  [0 2 4 6 8]

Linspace :  [ 0.   2.5  5.   7.5 10. ]

idetntity matrix :  [[1. 0.]
 [0. 1.]]

random array :  [[ 1.57027914 -1.03564792  0.31543567]
 [ 0.17913004  0.31087492  1.98121281]
 [-0.7013208   0.37515169 -0.61082959]]

randint :  [[7 0 1]
 [0 0 0]
 [5 7 8]]


Property array

In [11]:
arr = np.array([[1,2,3],[4,5,6]])

# shape ( bentuk array )
print("shape : ",arr.shape) # (2,3) = 2 baris, 3 kolom
print()

#Dimensi
print("dimensi", arr.ndim)  #2
print()

# jumlah elemen
print("jumlah elemen", arr.size) # 6
print()

# tipe data
print("tipe data :", arr.dtype)
print()

# ukuran perelemen ( bytes )
print("ukuran elemen : ", arr.itemsize) #8

shape :  (2, 3)

dimensi 2

jumlah elemen 6

tipe data : int64

ukuran elemen :  8


indexing & slciing

indexing

In [12]:
arr = np.array([10,20,30,40,50])

# akses elemen
print("akses elemen :", arr[0]) # 10
print("akses elemen :", arr[-1]) # 50 (dari belakang )

# 2D array
print("array 2D")
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d[0, 0]) # baris 1 kolom 1
print(arr2d[1, 2]) # baris 1 kolom 2
print(arr2d[-1,-1]) #baris terakhir kolom terakhir

akses elemen : 10
akses elemen : 50
array 2D
1
6
9


slicing

In [23]:
arr = np.array([10,20,30,40,50])

# [start:stop:step]
print(arr[1:4]) # [20,30,40 ] Mengambil index 1 sampai 3
print(arr[:3]) # Start default 0, stop ke index 2
print(arr[2:])  #Ambil dari index 2 sampai akhir
print(arr[::2]) #Ambil seluruh elemen dengan step 2
print()

# 2D slicing
"""
arr2d[rows, columns]
rows = start_row : stop_row
columns = start_col : stop_col
"""
print("2d slicing")
print()
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d[0:3, 2:3])  #arr2d[baris, kolom] 0:3  = index 0,1,2 . 3 sebagai stop tidak di hitung

[20 30 40]
[10 20 30]
[30 40 50]
[10 30 50]

2d slicing

[[3]
 [6]
 [9]]


** Boolean Indexing **

In [24]:
arr = np.array([1,2,3,4,5])

# fileter dengan kondisi
print(arr[arr > 3]) # 4.5
print(arr[arr % 2 == 0]) # 2,4


[4 5]
[2 4]


Reshaping array

In [27]:
arr = np.array([1,2,3,4,5,6])

# reshape ( ubah bentuk )
reshaped = arr.reshape(2,3) #2 baris 3 kolom
print("hasil reshape adalah : \n",reshaped)
print()

#flatten ( 1d )
flattten = reshaped.flatten() # 1,2,3,4,5,6
print("hasil flaten :\n", flattten)
print()

# ravel ( mrip dengan fltaen tapi view bukan coppy
raveled = reshaped.ravel()
print("hasil ravel : \n", raveled)
print()

# transpose ( balik baris jadi kolom
transpose = reshaped.T
print("hasil transpose : ", transpose)

hasil reshape adalah : 
 [[1 2 3]
 [4 5 6]]

hasil flaten :
 [1 2 3 4 5 6]

hasil ravel : 
 [1 2 3 4 5 6]

hasil transpose :  [[1 4]
 [2 5]
 [3 6]]


# **OPERASI MATEMATIKA**

OPERASI BASIC

In [ ]:
arr = np.array([1,2,3,4])

# operasi dengan scalar
print("operasi dengan sklaar")
print(arr  + 10)
print(arr * 2)
print(arr ** 2)
print(arr  / 2)
print()
# operasi dengan array
print("operasi dengan array")
arr2 = np.array([10,20,30,40])
print(arr + arr2)
print(arr * arr2)



FUNGSI MATEMATIKA

In [32]:
arr = np.array([1,2,3,4,5])
print("nilai array : ",arr)

#agregasi
print(np.sum(arr)) # jumlah
print(np.mean(arr)) # rata rata
print(np.std(arr)) # standar deviation
print()
print()
print()
print()

nilai array :  [1 2 3 4 5]





