In [2]:
import numpy as np
print(np.__version__)

2.0.2


**MEMBUAT ARRAY**

dari list/tuple

In [3]:
#1D array
arr1 = np.array([1,2,3,4,5])

# 2D array ( matrix)
arr2 = np.array([
    [1,2,3],
    [4,5,6]])

#3D array
arr3 = np.array([[[1,2],
                  [3,4],
                  [5,6]]])

**Array Khusus **

In [4]:
# array nol
zeros = np.zeros((3,4))
print("zeros : ", zeros)
print()

# array 1
ones = np.ones((3,4))
print("ones : ", ones)
print()

# arra7 kosong ( random value )
empty = np.empty((2,2))
print("empty : ", empty)
print()

#array dengan range
range_arr = np.arange(0,10,2)
print("range : ", range_arr)
print()

# array dengan spacing merata
linespace = np.linspace(0,10,5) # 5 nilai dari 0 - 10
print(f"Linspace : ", linespace)
print()

# indetitiy matrix
identity = np.eye(2) # matrix 3 x 3
print("idetntity matrix : ", identity)
print()

# array random
random_Arr = np.random.randn(3,3) #nilai 0-1
print("random array : ",random_Arr)
print()
random_int = np.random.randint(0,10, (3,3))  # integer random
print("randint : ", random_int)



zeros :  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

ones :  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

empty :  [[6.23042070e-307 4.67296746e-307]
 [1.69121096e-306 1.34399069e-311]]

range :  [0 2 4 6 8]

Linspace :  [ 0.   2.5  5.   7.5 10. ]

idetntity matrix :  [[1. 0.]
 [0. 1.]]

random array :  [[ 1.03218736 -0.35495892 -0.14336379]
 [-0.67845606 -0.47556265  1.28701952]
 [-1.36515947 -0.571428    1.06749326]]

randint :  [[8 9 0]
 [5 3 8]
 [1 9 7]]


Property array

In [5]:
arr = np.array([[1,2,3],[4,5,6]])

# shape ( bentuk array )
print("shape : ",arr.shape) # (2,3) = 2 baris, 3 kolom
print()

#Dimensi
print("dimensi", arr.ndim)  #2
print()

# jumlah elemen
print("jumlah elemen", arr.size) # 6
print()

# tipe data
print("tipe data :", arr.dtype)
print()

# ukuran perelemen ( bytes )
print("ukuran elemen : ", arr.itemsize) #8

shape :  (2, 3)

dimensi 2

jumlah elemen 6

tipe data : int64

ukuran elemen :  8


indexing & slciing

indexing

In [6]:
arr = np.array([10,20,30,40,50])

# akses elemen
print("akses elemen :", arr[0]) # 10
print("akses elemen :", arr[-1]) # 50 (dari belakang )

# 2D array
print("array 2D")
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d[0, 0]) # baris 1 kolom 1
print(arr2d[1, 2]) # baris 1 kolom 2
print(arr2d[-1,-1]) #baris terakhir kolom terakhir

akses elemen : 10
akses elemen : 50
array 2D
1
6
9


slicing

In [7]:
arr = np.array([10,20,30,40,50])

# [start:stop:step]
print(arr[1:4]) # [20,30,40 ] Mengambil index 1 sampai 3
print(arr[:3]) # Start default 0, stop ke index 2
print(arr[2:])  #Ambil dari index 2 sampai akhir
print(arr[::2]) #Ambil seluruh elemen dengan step 2
print()

# 2D slicing
"""
arr2d[rows, columns]
rows = start_row : stop_row
columns = start_col : stop_col
"""
print("2d slicing")
print()
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d[0:3, 2:3])  #arr2d[baris, kolom] 0:3  = index 0,1,2 . 3 sebagai stop tidak di hitung

[20 30 40]
[10 20 30]
[30 40 50]
[10 30 50]

2d slicing

[[3]
 [6]
 [9]]


** Boolean Indexing **

In [8]:
arr = np.array([1,2,3,4,5])

# fileter dengan kondisi
print(arr[arr > 3]) # 4.5
print(arr[arr % 2 == 0]) # 2,4


[4 5]
[2 4]


Reshaping array

In [9]:
arr = np.array([1,2,3,4,5,6])

# reshape ( ubah bentuk )
reshaped = arr.reshape(2,3) #2 baris 3 kolom
print("hasil reshape adalah : \n",reshaped)
print()

#flatten ( 1d )
flattten = reshaped.flatten() # 1,2,3,4,5,6
print("hasil flaten :\n", flattten)
print()

# ravel ( mrip dengan fltaen tapi view bukan coppy
raveled = reshaped.ravel()
print("hasil ravel : \n", raveled)
print()

# transpose ( balik baris jadi kolom
transpose = reshaped.T
print("hasil transpose : ", transpose)

hasil reshape adalah : 
 [[1 2 3]
 [4 5 6]]

hasil flaten :
 [1 2 3 4 5 6]

hasil ravel : 
 [1 2 3 4 5 6]

hasil transpose :  [[1 4]
 [2 5]
 [3 6]]


# **OPERASI MATEMATIKA**

OPERASI BASIC

In [10]:
arr = np.array([1,2,3,4])

# operasi dengan scalar
print("operasi dengan sklaar")
print(arr  + 10)
print(arr * 2)
print(arr ** 2)
print(arr  / 2)
print()
# operasi dengan array
print("operasi dengan array")
arr2 = np.array([10,20,30,40])
print(arr + arr2)
print(arr * arr2)



operasi dengan sklaar
[11 12 13 14]
[2 4 6 8]
[ 1  4  9 16]
[0.5 1.  1.5 2. ]

operasi dengan array
[11 22 33 44]
[ 10  40  90 160]


FUNGSI MATEMATIKA

In [11]:
arr = np.array([1,2,3,4,5])
print("nilai array : ",arr)

#agregasi
print(np.sum(arr)) # jumlah
print(np.mean(arr)) # rata rata
print(np.std(arr)) # standar deviation
print(np.var(arr))  # variance
print(np.min(arr))  # 1
print(np.max(arr))  # 5
print()
print("INDEX MIN/ MAX")
print()
print(np.argmin(arr))
print(np.argmax(arr))
print()
print("Kumulatif")
print()
print(np.cumsum(arr))
print()

print("universal function")
print()
print(np.sqrt(arr))
print(np.exp(arr))
print(np.log(arr))
print(np.sin(arr))

nilai array :  [1 2 3 4 5]
15
3.0
1.4142135623730951
2.0
1
5

INDEX MIN/ MAX

0
4

Kumulatif

[ 1  3  6 10 15]

universal function

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


# **Operasi 2D**

In [12]:
arr2d = np.array([[1,2,3],[4,5,6]])
print(arr2d)

print("Sum per axis")
print(np.sum(arr2d, axis = 0))  # sum kolom
print(np.sum(arr2d, axis = 1))  #sum baris

print("Mean per axis")
print(np.mean(arr2d, axis = 0))
print(np.mean(arr2d, axis = 1))

[[1 2 3]
 [4 5 6]]
Sum per axis
[5 7 9]
[ 6 15]
Mean per axis
[2.5 3.5 4.5]
[2. 5.]


# Array manipulation

In [13]:
print("Concatenate ( Gabung )")
print()

arr1 = np.array([1,2,3,4])
arr2 = np.array([4,5,6,7])

print("Gabung horizontal")
result = np.concatenate([arr1, arr2])
print(result)

print("Gabung 2 d")
arr2d = np.array([[1,2],[3,4]])
arr2d_2 = np.array([[5,6],[7,8]])
result2 = np.concatenate([arr2d, arr2d_2])
print(result2)

print()
print("vertical stack")
vstack = np.vstack([arr2d, arr2d_2])
print(vstack)

print()
print("horizontal stack")
hstack = np.hstack([arr2d, arr2d_2])
print(hstack)

print()
print("split")
arr = np.array([1,2,3,4,5,6,7,8,9])
split = np.split(arr,3)
print(split)

Concatenate ( Gabung )

Gabung horizontal
[1 2 3 4 4 5 6 7]
Gabung 2 d
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

vertical stack
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

horizontal stack
[[1 2 5 6]
 [3 4 7 8]]

split
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


# Broadcasting
operasi array dengan shape yang berbeda

In [14]:
print("Contoh 1")
arr = np.array([[1,2,3],[4,5,6]])
scallar = 10
result = arr + scallar
print(result)

print()
print("Contoh 2")
row = np.array([10,20,30])
result1 = arr + row
print(result1)

Contoh 1
[[11 12 13]
 [14 15 16]]

Contoh 2
[[11 22 33]
 [14 25 36]]


# sorting dan searching

In [15]:
arr = np.array([4,6,2,7,23,75,4])
print("array : ",arr)
print()

print("SORT")
sorted = np.sort(arr)
print(sorted)
print()

print("argsort ( index urutan )")
indices = np.argsort(arr)
print(indices)

print()
print("where ( cari index yang memenuhi kondisi )")
inicess = np.where(arr > 4)
print(inicess)

array :  [ 4  6  2  7 23 75  4]

SORT
[ 2  4  4  6  7 23 75]

argsort ( index urutan )
[2 0 6 1 3 4 5]

where ( cari index yang memenuhi kondisi )
(array([1, 3, 4, 5]),)


# copy vs view

In [17]:
arr = np.array([1,2,3,4,5])

print("VIEW : REFRENSI, PERUBAHAN AFFECT ORIGINAL")
print()

view = arr[:]
view[0] = 100
print(arr)
print()

print("COPPY ( INDEPENDENT, GA EFECT ORIGINAL")
coppy = arr.copy()
coppy[0] = 999
print(arr)

VIEW : REFRENSI, PERUBAHAN AFFECT ORIGINAL

[100   2   3   4   5]

COPPY ( INDEPENDENT, GA EFECT ORIGINAL
[100   2   3   4   5]


## TIPS PENTING
# KENAPA NUMPY LEBIH CEPAT DARIPADA LIST?

In [21]:
print("List pytohn ( lambat )")
list_Data = [1,2,2,4,4]
result = [x * 2 for x in list_Data]
print(result)
print()

print("Numpy ( lebih cepat - vectorized ) ")
np_dta = np.array([14,523,73,125,47,52])
result = np_dta * 2
print(result)

List pytohn ( lambat )
[2, 4, 4, 8, 8]

Numpy ( lebih cepat - vectorized ) 
[  28 1046  146  250   94  104]


# memory efficeint

In [23]:
print("Numpy pakai type fixed, artinya lebih hermat memory")
arr = np.array([13,124,62,42])  # 8 bit integer

print()
print("Numpy sering dipake di ml")
data = np.array([53,25,62,57,52,6])
normalized = (data - np.mean(data)) / np.std(data)
print(normalized)

Numpy pakai type fixed, artinya lebih hermat memory

Numpy sering dipake di ml
[ 0.52180288 -0.86967147  0.96906249  0.72058493  0.47210737 -1.81388621]


# latihan

In [ ]:
print("array 1 - 100")
a = np.random.randint(1,100,100)