In [2]:
import numpy as np
from networkx.algorithms.threshold import eigenvectors

# ARRAY DARI LIST

In [4]:
arr_list = np.array([1,2,3,4,5,6,7])
print(arr_list)
arr_list = np.array([1,2,3,4,5,6,7])
print(type(arr_list))

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


# ARRAY 1 D

In [6]:
a1 = np.array([1,2,3,4,4,3,3,42,3])
a1

array([ 1,  2,  3,  4,  4,  3,  3, 42,  3])

# ARRAY 2D ( MATRIKS )

In [5]:
a2 = np.array([[1,2,3],[24,12,43]])
a2

array([[ 1,  2,  3],
       [24, 12, 43]])

# ARRAY 3D( TEMSPR - PENTING UNTUK DEEP LEARNING ) !

In [8]:
a3 = np.array([[[1,2],[2,3],[53,35]]])
print(a3)

[[[ 1  2]
  [ 2  3]
  [53 35]]]


# PEMBUATAN ARRAY PRAKTIS

In [11]:
zeros = np.zeros((3,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
ones = np.ones((3,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
arange = np.arange(0,5,2)
arange

array([0, 2, 4])

In [19]:
linspace = np.linspace(0,1,5)
linspace

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [20]:
random_arr = np.random.rand(3,3)
random_arr

array([[0.03389832, 0.03482772, 0.12688968],
       [0.3250516 , 0.92389728, 0.63890295],
       [0.75603562, 0.14425702, 0.81240755]])

In [21]:
eye =  np.eye(4)
eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# ATRIBUTE ARRAY ( WAJIB PAHAM )

In [25]:
arr = np.array([[1,2,3,4],[2,25,7,4],[8,6,5,4]])
print(arr)

[[ 1  2  3  4]
 [ 2 25  7  4]
 [ 8  6  5  4]]


In [26]:
arr.shape # liat shape

(3, 4)

In [27]:
arr.ndim

2

In [28]:
arr.size

12

In [29]:
arr.dtype

dtype('int32')

# RESHAPE PENTING UNTUK DEEPLEARNING

In [34]:
reshaped = arr.reshape(4,3)
print(reshaped)

[[ 1  2  3]
 [ 4  2 25]
 [ 7  4  8]
 [ 6  5  4]]


In [35]:
flatten = arr.flatten()
print(flatten)

[ 1  2  3  4  2 25  7  4  8  6  5  4]


# INDEXING SLICING

In [36]:
arr = np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [37]:
arr[0]

10

In [38]:
arr[-1]

50

In [39]:
arr[1:4]

array([20, 30, 40])

# 2D INDEXING

In [40]:
a2d = np.array([[1,2,3],[24,12,43],[2,5,7]])
a2d

array([[ 1,  2,  3],
       [24, 12, 43],
       [ 2,  5,  7]])

In [41]:
a2d[0,0]

1

In [42]:
a2d[1,2]

43

In [43]:
a2d[0, :]

array([1, 2, 3])

In [44]:
a2d[:, 1]

array([ 2, 12,  5])

In [45]:
a2d[0:2, 1:3]

array([[ 2,  3],
       [12, 43]])

# BOOLEAN INDEXING

In [47]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [48]:
arr[arr > 3]

array([4, 5, 6])

In [49]:
arr[arr % 2 == 0]

array([2, 4, 6])

# OPERASI MATEMATIKA

OPERASI ANTAR ARRAY

In [50]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])


array([4, 5, 6])

In [51]:
arr1 + arr2

array([5, 7, 9])

In [52]:
arr1 * arr2

array([ 4, 10, 18])

# FUNGSI AGREGASI

In [54]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
np.sum(arr)

21

In [56]:
np.sum(arr, axis=0)

array([5, 7, 9])

In [59]:
np.sum(arr, axis=1)

array([ 6, 15])

In [60]:
np.mean(arr)

3.5

In [61]:
np.min(arr)

1

In [62]:
np.std(arr)

1.707825127659933

# LINEAR ALGERBBRA PENTING UNTUK ML



dor product / matrix multiplication

In [64]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [65]:
a @ b   # atau np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [66]:
a.T # transpose

array([[1, 3],
       [2, 4]])

# DETERMINAN

In [68]:
DET = np.linalg.det(a)
DET

-2.0000000000000004

# INVERSE

In [69]:
inv = np.linalg.inv(a)
inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

# Eigenvalues & Eigenvectors (untuk PCA!)

In [72]:
eigenvalues , eigenvectors = np.linalg.eig(a)
print(eigenvalues)

[-0.37228132  5.37228132]


In [73]:
eigenvectors

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])

# BROADCASTING

In [87]:
arr = np.array([[1,2],[4,5],[6,7]])

In [74]:
arr + 10

array([[11, 12, 13],
       [14, 15, 16]])

# TAMBAH DENGAN 1D ARRAY

In [88]:
arr1d = np.array([[1,2],[3,4],[5,6]])

In [89]:
arr + arr1d

array([[ 2,  4],
       [ 7,  9],
       [11, 13]])

# NORMALISASI DATA ( TEKNIK UMUM ML )

In [94]:
data = np.array([[1,2],[3,4],[5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [102]:
mean = np.mean(data, axis=0)
mean

array([3., 4.])

In [103]:
std = np.std(data, axis=0)
std

array([1.63299316, 1.63299316])

In [104]:
normalized = (data - mean) / std # Broadcasting
normalized

array([[-2., -2.],
       [ 0.,  0.],
       [ 2.,  2.]])

# ADVANCED - STACKONG & SPLITING

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

# VERTIKAL STACKING

In [105]:
vstacked = np.vstack((arr1,arr2))
vstacked

array([[1, 2, 3],
       [4, 5, 6]])

# HORIZONTAL STACKING

In [106]:
h = np.hstack((arr1,arr2))
h

array([1, 2, 3, 4, 5, 6])

# splitting

In [107]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [108]:
np.split(arr, 3, axis=0)    # split 3 bagian

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

# case 1

In [109]:
# Kasus 1: Normalisasi gambar (0-255 ke 0-1)
image = np.random.randint(0,256, ( 5,5))
print("IMAGE PIXEL VALUES : \n", image)

IMAGE PIXEL VALUES : 
 [[141 148  65  86   8]
 [212 143 172  24  30]
 [124 138 233 101 121]
 [ 31  75 113 136 236]
 [ 91  52  44  64 255]]


In [110]:
normalized_img = image / 255.0
print("NORMALIZED ( 0- 1) : ", normalized_img)

NORMALIZED ( 0- 1) :  [[0.55294118 0.58039216 0.25490196 0.3372549  0.03137255]
 [0.83137255 0.56078431 0.6745098  0.09411765 0.11764706]
 [0.48627451 0.54117647 0.91372549 0.39607843 0.4745098 ]
 [0.12156863 0.29411765 0.44313725 0.53333333 0.9254902 ]
 [0.35686275 0.20392157 0.17254902 0.25098039 1.        ]]


# Kasus 2: One-hot encoding (untuk neural networks!)

In [111]:
labels = np.array([0,1,2,1,0])
num_classes = 3
one_hot = np.eye(num_classes) [labels]


In [112]:
print(labels)

[0 1 2 1 0]


In [113]:
print(one_hot)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


# Kasus 3: Batch processing (seperti di deep learning)

In [114]:
batch_size = 32
image_height = 28
image_width = 28
chanell = 3
batch_images = np.random.rand(batch_size, image_height, image_width, chanell)

In [115]:
batch_images.shape

(32, 28, 28, 3)

# Copy vs View

In [117]:
arr = np.array([1,2,3])

In [118]:
view = arr.view()   # masih terhubung

In [119]:
copy = arr.copy()   # independn

In [120]:
arr[0] = 999

In [121]:
arr

array([999,   2,   3])

In [122]:
view

array([999,   2,   3])

In [123]:
copy

array([1, 2, 3])

#   WHERE ( CONDITIONAL )

In [124]:
arr = np.array([1,2,3,4,5,6])
result = np.where(arr > 2, arr, 0) # jika >2 ambil ilai, else 0

In [125]:
result

array([0, 0, 3, 4, 5, 6])

# unique values

In [126]:
arr = np.array([1, 1, 2, 2, 3, 3, 3])
unique = np.unique(arr, return_counts=True)
unique

(array([1, 2, 3]), array([2, 2, 3], dtype=int64))

# ARGSMAX , ARGSMIN

In [127]:
arr = np.array([13,53,75,689,25,25,25])
arr

array([ 13,  53,  75, 689,  25,  25,  25])

In [128]:
np.argmax((arr))

3

In [129]:
np.argmin(arr)

0